import { Link } from 'react-router-dom'
import { useLang } from '../LangContext'

// ── Odysight pre-fill URL ─────────────────────────────────────────────────────

const ODYSIGHT_CLAIM_FR = 'Odysight détecte précocement les évolutions de l\'acuité visuelle chez les patients DMLA et améliore la prise en charge ophtalmologique.'
const ODYSIGHT_CLAIM_EN = 'Odysight detects early changes in visual acuity in AMD patients and improves ophthalmological management.'

const ODYSIGHT_REPAIR_URL = `/odysight/repair?intervention=Odysight&domain=Ophtalmologie&claim=${encodeURIComponent(ODYSIGHT_CLAIM_FR)}`

// ── Engine pillars ─────────────────────────────────────────────────────────────

const ENGINE_PILLARS_FR = [
  {
    title: 'Structure causale de la revendication',
    desc: 'Le niveau de preuve implicite est-il cohérent avec le type d\'affirmation ? Une revendication d\'outcome clinique n\'est pas soutenue par les mêmes exigences de design qu\'une revendication de performance.',
  },
  {
    title: 'Indépendance de la mesure',
    desc: 'Le dispositif influence-t-il directement la façon dont l\'effet est mesuré ? Un critère généré ou déclenché par le dispositif lui-même ne permet pas une inférence causale indépendante.',
  },
  {
    title: 'Compatibilité design ↔ revendication',
    desc: 'Le design permet-il réellement une inférence causale au niveau revendiqué ? Un design exploratoire ne démontre pas un outcome clinique. Un essai sans comparateur ne soutient pas une revendication d\'efficacité.',
  },
  {
    title: 'Cohérence dispositif ↔ population ↔ contexte',
    desc: 'L\'étude évalue-t-elle le bon dispositif, dans le bon usage, sur la bonne population ? Un écart à ce niveau fragilise la validité externe indépendamment de la qualité interne de l\'étude.',
  },
]

const ENGINE_PILLARS_EN = [
  {
    title: 'Causal structure of the claim',
    desc: 'Is the implicit level of evidence consistent with the type of claim? An outcome-level claim requires different design requirements than a performance-level one.',
  },
  {
    title: 'Independence of measurement',
    desc: 'Does the device directly influence how the effect is measured? An endpoint generated or triggered by the device itself does not allow independent causal inference.',
  },
  {
    title: 'Design ↔ claim compatibility',
    desc: 'Does the design actually allow causal inference at the claimed level? An exploratory design does not demonstrate a clinical outcome. A single-arm study does not support an efficacy claim.',
  },
  {
    title: 'Device ↔ population ↔ context consistency',
    desc: 'Does the study evaluate the right device, in the right use, on the right population? A gap at this level weakens external validity regardless of the internal quality of the study.',
  },
]

// ── Odysight-specific example gaps ────────────────────────────────────────────

const EXAMPLE_GAPS_FR = [
  {
    label: 'Indépendance de la mesure',
    desc: 'La détection d\'une évolution visuelle est générée par Odysight lui-même. Le critère dépend de la sensibilité algorithmique de l\'application — pas d\'une mesure indépendante de l\'évolution clinique réelle.',
  },
  {
    label: 'Design',
    desc: 'Étude en bras unique. Sans groupe contrôle concurrent, les évolutions détectées ne peuvent être distinguées de l\'histoire naturelle de la DMLA ou de l\'effet des injections anti-VEGF concomitantes.',
  },
  {
    label: 'Niveau de preuve',
    desc: 'Un design exploratoire génère des données de faisabilité sur les paramètres de détection — il ne soutient pas une revendication d\'amélioration de la prise en charge clinique.',
  },
]

const EXAMPLE_GAPS_EN = [
  {
    label: 'Independence of measurement',
    desc: 'The detection of visual changes is generated by Odysight itself. The endpoint depends on the algorithm\'s sensitivity — not an independent measure of actual clinical evolution.',
  },
  {
    label: 'Design',
    desc: 'Single-arm study. Without a concurrent control group, detected changes cannot be distinguished from the natural history of AMD or the effect of concomitant anti-VEGF injections.',
  },
  {
    label: 'Level of evidence',
    desc: 'An exploratory design generates feasibility data on detection parameters — it does not support a claim of improved clinical management.',
  },
]

// ── Component ─────────────────────────────────────────────────────────────────

export default function LandingOdysight() {
  const { lang } = useLang()
  const fr = lang === 'fr'

  const enginePillars = fr ? ENGINE_PILLARS_FR : ENGINE_PILLARS_EN
  const exampleGaps   = fr ? EXAMPLE_GAPS_FR   : EXAMPLE_GAPS_EN

  return (
    <div>

      {/* ── DEMO BANNER ──────────────────────────────────────────────────────── */}
      <div className="bg-accent/10 border-b border-accent/20 px-6 py-3 text-center">
        <p className="text-sm text-accent font-medium">
          {fr
            ? 'Accès démo personnalisé — Tilak Healthcare / Odysight · Accès complet, sans restriction, pour votre évaluation'
            : 'Personalised demo access — Tilak Healthcare / Odysight · Full access, no restrictions, for your evaluation'}
        </p>
      </div>

      {/* ── HERO ─────────────────────────────────────────────────────────────── */}
      <section className="bg-gradient-to-br from-primary to-primary-light text-white py-24 px-6 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,255,255,0.05)_0%,transparent_50%)]" />
        <div className="max-w-4xl mx-auto text-center relative">

          <div className="inline-block bg-white/10 rounded-full px-4 py-1.5 text-sm font-medium mb-10 backdrop-blur-sm">
            {fr
              ? 'Dispositifs médicaux · Ophtalmologie · Accès au marché'
              : 'Medical devices · Ophthalmology · Market access'}
          </div>

          <h1 className="text-4xl md:text-5xl font-bold mb-5 leading-tight max-w-3xl mx-auto">
            {fr
              ? 'Détectez et corrigez les fragilités méthodologiques de vos études RCT et RWE avant soumission.'
              : 'Detect and correct the methodological weaknesses in your RCT and RWE studies before submission.'}
          </h1>

          <p className="text-lg text-white/85 mb-6 max-w-2xl mx-auto leading-relaxed">
            {fr
              ? 'EvidenceAble analyse la cohérence entre une revendication et les preuves qui la soutiennent. Il reconstruit la logique de la revendication, identifie le niveau de preuve qu\'elle implique, et applique des règles explicites de causalité et de validité de mesure.'
              : 'EvidenceAble analyses the coherence between a claim and the evidence supporting it. It reconstructs the logic of the claim, identifies the level of evidence it implies, and applies explicit rules of causality and measurement validity.'}
          </p>

          <div className="bg-white/10 backdrop-blur-sm rounded-xl px-6 py-4 mb-8 max-w-xl mx-auto border border-white/15">
            <p className="text-white/85 text-sm leading-relaxed">
              {fr
                ? 'Un seul moteur épistémique. Deux niveaux d\'analyse selon les informations que vous fournissez — revendication seule, ou revendication et données cliniques.'
                : 'One epistemic engine. Two levels of analysis depending on the information you provide — claim alone, or claim and clinical data.'}
            </p>
          </div>

          <div className="flex gap-4 justify-center flex-wrap">
            <Link
              to="/odysight/review"
              className="bg-white/15 hover:bg-white/25 text-white px-8 py-3.5 rounded-xl font-semibold text-lg transition-colors backdrop-blur-sm border border-white/20 text-left"
            >
              <span className="block">→ {fr ? 'Analyse rapide' : 'Quick analysis'}</span>
              <span className="block text-xs text-white/60 font-normal mt-0.5">
                {fr ? 'À partir de votre revendication' : 'From your claim'}
              </span>
            </Link>
            <Link
              to={ODYSIGHT_REPAIR_URL}
              className="bg-accent hover:bg-accent/90 text-white px-8 py-3.5 rounded-xl font-semibold text-lg transition-colors shadow-lg shadow-accent/30 text-left"
            >
              <span className="block">→ {fr ? 'Analyse complète' : 'Full analysis'}</span>
              <span className="block text-xs text-white/60 font-normal mt-0.5">
                {fr ? 'Revendication + données cliniques' : 'Claim + clinical data'}
              </span>
            </Link>
          </div>
        </div>
      </section>

      {/* ── PROBLÈME ─────────────────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-primary text-center mb-6">
            {fr
              ? 'Un dossier peut être robuste — et ne pas constituer une preuve.'
              : 'A dossier can be robust — and still not constitute evidence.'}
          </h2>
          <p className="text-center text-gray-500 mb-10 leading-relaxed">
            {fr
              ? 'Dans de nombreux projets cliniques, le problème n\'est pas la qualité des données. C\'est le décalage entre ce que la source de données mesure et ce que la revendication affirme — qu\'il s\'agisse d\'un essai randomisé, d\'une cohorte observationnelle ou de données en vie réelle.'
              : 'In many clinical projects, the problem is not the quality of the data. It is the gap between what the data source measures and what the claim asserts — whether it is a randomised trial, an observational cohort or real-world data.'}
          </p>

          <div className="space-y-3 mb-10">
            {(fr
              ? [
                  'Une efficacité évaluée avec un critère non indépendant de l\'intervention.',
                  'Un design exploratoire utilisé pour soutenir une conclusion causale.',
                  'Un proxy interprété comme un bénéfice clinique direct.',
                  'Des données qui répondent à une question différente de celle posée par la revendication.',
                ]
              : [
                  'Efficacy evaluated with an endpoint that is not independent of the intervention.',
                  'An exploratory design used to support a causal conclusion.',
                  'A proxy interpreted as a direct clinical benefit.',
                  'Data that answers a different question from the one posed by the claim.',
                ]
            ).map((item, i) => (
              <div key={i} className="flex items-start gap-4 bg-gray-50 border border-gray-100 rounded-xl px-6 py-4">
                <span className="text-gray-300 font-bold mt-0.5 flex-shrink-0 text-lg">×</span>
                <p className="text-gray-700 text-sm leading-relaxed">{item}</p>
              </div>
            ))}
          </div>

          <p className="text-center text-gray-400 text-sm mb-8 italic">
            {fr
              ? 'Dans ces cas, ajouter des données ne corrige pas le problème.'
              : 'In these cases, adding more data does not fix the problem.'}
          </p>

          <div className="bg-primary/5 border-2 border-primary/15 rounded-xl px-8 py-6 text-center">
            <p className="text-primary font-semibold text-lg leading-relaxed">
              {fr
                ? 'La question centrale devient : votre source de données a-t-elle été conçue pour démontrer ce que vous affirmez ?'
                : 'The central question becomes: was your data source designed to demonstrate what you claim?'}
            </p>
          </div>
        </div>
      </section>

      {/* ── CE QUE FAIT EvidenceAble ─────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-surface border-y border-gray-100">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-primary text-center mb-4">
            {fr
              ? 'Un moteur de cohérence entre revendication et preuve clinique'
              : 'An engine for coherence between claim and clinical evidence'}
          </h2>
          <p className="text-center text-gray-500 mb-4 max-w-2xl mx-auto text-sm leading-relaxed">
            {fr
              ? 'EvidenceAble analyse la structure logique entre une revendication et un dossier de preuve — essai randomisé, cohorte, registre ou RWE. Il n\'interprète pas librement. Il applique un ensemble de règles explicites fondées sur des principes méthodologiques.'
              : 'EvidenceAble analyses the logical structure between a claim and an evidence dossier — randomised trial, cohort, registry or RWE. It does not interpret freely. It applies a set of explicit rules based on methodological principles.'}
          </p>
          <p className="text-center text-gray-400 text-xs mb-12 italic">
            {fr
              ? 'Chaque écart identifié est relié à une règle explicite. Chaque conclusion est traçable et reproductible.'
              : 'Each identified gap is linked to an explicit rule. Every conclusion is traceable and reproducible.'}
          </p>

          <div className="grid md:grid-cols-2 gap-5">
            {enginePillars.map((p, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-100 p-6 shadow-sm">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-7 h-7 bg-primary/10 rounded-lg flex items-center justify-center flex-shrink-0">
                    <span className="text-primary font-bold text-sm">{i + 1}</span>
                  </div>
                  <h3 className="font-semibold text-gray-800">{p.title}</h3>
                </div>
                <p className="text-sm text-gray-500 leading-relaxed">{p.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── COMMENT ÇA FONCTIONNE ────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-primary text-center mb-4">
            {fr ? 'Deux niveaux d\'analyse' : 'Two levels of analysis'}
          </h2>
          <p className="text-center text-gray-500 text-sm mb-2 max-w-lg mx-auto font-medium">
            {fr
              ? 'Le même moteur. Plus ou moins d\'informations selon votre besoin.'
              : 'The same engine. More or less information depending on your need.'}
          </p>
          <p className="text-center text-gray-400 text-xs mb-14 max-w-md mx-auto">
            {fr
              ? 'Vous pouvez utiliser l\'analyse rapide seule, l\'analyse complète directement, ou les deux — dans n\'importe quel ordre.'
              : 'You can use quick analysis alone, start directly with full analysis, or both — in any order.'}
          </p>

          {/* Analyse rapide */}
          <div className="mb-8 rounded-2xl border-2 border-primary/20 overflow-hidden shadow-sm">
            <div className="bg-primary/5 border-b border-primary/10 px-8 py-5 flex items-center gap-4">
              <span className="bg-primary text-white text-xs font-bold px-3 py-1.5 rounded-full uppercase tracking-wide">
                {fr ? 'Analyse rapide — Accès libre' : 'Quick analysis — Open access'}
              </span>
              <h3 className="text-xl font-bold text-primary">
                {fr
                  ? 'À partir de votre revendication clinique'
                  : 'From your clinical claim'}
              </h3>
            </div>
            <div className="grid md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-gray-100">
              <div className="p-6">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                  {fr ? 'Entrée' : 'Input'}
                </p>
                <p className="text-sm text-gray-600 leading-relaxed mb-4">
                  {fr
                    ? 'Décrivez votre revendication clinique en texte libre : dispositif, indication, effet attendu, type d\'évaluation.'
                    : 'Describe your clinical claim in free text: device, indication, expected effect, type of evaluation.'}
                </p>
                <div className="bg-gray-50 rounded-lg border border-gray-200 p-3 font-mono text-xs text-gray-400 italic">
                  {fr
                    ? '"Odysight améliore la détection précoce des évolutions maculaires chez les patients DMLA."'
                    : '"Odysight improves early detection of macular changes in AMD patients."'}
                </div>
              </div>
              <div className="p-6">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                  {fr ? 'Sortie' : 'Output'}
                </p>
                <div className="space-y-2.5">
                  {(fr
                    ? ['Niveau de revendication (A → D)', 'Structure causale classifiée', 'Points de fragilité méthodologique', 'Type de design généralement nécessaire']
                    : ['Claim level (A → D)', 'Classified causal structure', 'Methodological fragility points', 'Type of study design typically required']
                  ).map((item, i) => (
                    <div key={i} className="flex gap-2 text-sm text-gray-600">
                      <span className="text-primary font-bold flex-shrink-0">·</span> {item}
                    </div>
                  ))}
                </div>
              </div>
              <div className="p-6 bg-primary/3 flex flex-col justify-between">
                <div>
                  <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                    {fr ? 'Valeur' : 'Value'}
                  </p>
                  <p className="text-sm text-primary font-medium leading-relaxed">
                    {fr
                      ? 'Savoir en quelques secondes si une revendication est cohérente avec un cadre de preuve — avant de concevoir ou de sélectionner une source de données.'
                      : 'Know in seconds whether a claim is consistent with an evidence framework — before designing or selecting a data source.'}
                  </p>
                </div>
                <Link
                  to="/odysight/review"
                  className="mt-6 inline-block bg-primary hover:bg-primary-light text-white px-6 py-2.5 rounded-xl font-medium transition-colors text-center text-sm"
                >
                  {fr ? 'Tester ma revendication →' : 'Test my claim →'}
                </Link>
              </div>
            </div>
          </div>

          {/* Analyse complète */}
          <div className="rounded-2xl border-2 border-accent/30 overflow-hidden shadow-sm">
            <div className="bg-accent/5 border-b border-accent/20 px-8 py-5 flex items-center gap-4">
              <span className="bg-accent text-white text-xs font-bold px-3 py-1.5 rounded-full uppercase tracking-wide">
                {fr ? 'Analyse complète — Accès démo' : 'Full analysis — Demo access'}
              </span>
              <h3 className="text-xl font-bold text-accent">
                {fr
                  ? 'À partir de votre revendication et de vos données cliniques'
                  : 'From your claim and clinical data'}
              </h3>
            </div>
            <div className="grid md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-gray-100">
              <div className="p-6">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                  {fr ? 'Entrée' : 'Input'}
                </p>
                <p className="text-sm text-gray-600 leading-relaxed mb-4">
                  {fr
                    ? 'Revendication + abstract ou PDF (≤ 5 pages) — essai, cohorte, registre ou RWE. Le moteur extrait et structure les éléments méthodologiques clés.'
                    : 'Claim + abstract or PDF (≤ 5 pages) — trial, cohort, registry or RWE. The engine extracts and structures the key methodological elements.'}
                </p>
                <div className="space-y-1">
                  {(fr
                    ? ['Dispositif étudié', 'Design · Randomisation · Aveugle · Comparateur', 'Population · Contexte · Durée de suivi', 'Endpoints principaux']
                    : ['Device studied', 'Design · Randomisation · Blinding · Comparator', 'Population · Context · Follow-up', 'Primary endpoints']
                  ).map((item, i) => (
                    <div key={i} className="flex gap-2 text-xs text-gray-500">
                      <span className="text-accent font-bold">·</span> {item}
                    </div>
                  ))}
                </div>
              </div>
              <div className="p-6">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                  {fr ? 'Sortie' : 'Output'}
                </p>
                <div className="space-y-2">
                  {(fr
                    ? [
                        'Analyse des écarts par dimension : device · population · design · endpoints · causalité',
                        'Identification des incohérences structurelles',
                        'Plan de correction priorisé : immédiat · amendement · nouvelle étude',
                        'Export PDF du rapport',
                      ]
                    : [
                        'Gap analysis by dimension: device · population · design · endpoints · causality',
                        'Identification of structural incoherences',
                        'Prioritised correction plan: immediate · amendment · new study',
                        'Full report PDF export',
                      ]
                  ).map((item, i) => (
                    <div key={i} className="flex gap-2 text-sm text-gray-600">
                      <span className="text-accent font-bold flex-shrink-0">·</span> {item}
                    </div>
                  ))}
                </div>
              </div>
              <div className="p-6 bg-accent/3 flex flex-col justify-between">
                <div>
                  <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">
                    {fr ? 'Valeur' : 'Value'}
                  </p>
                  <p className="text-sm text-accent font-medium leading-relaxed">
                    {fr
                      ? 'Savoir si un design ou une source de données est suffisant pour une revendication donnée — ou identifier les ajustements méthodologiques nécessaires avant de décider.'
                      : 'Know whether a design or data source is sufficient for a given claim — or identify the methodological adjustments needed before deciding.'}
                  </p>
                </div>
                <Link
                  to={ODYSIGHT_REPAIR_URL}
                  className="mt-6 inline-block bg-accent hover:bg-accent/90 text-white px-6 py-2.5 rounded-xl font-medium transition-colors text-center shadow-md shadow-accent/20 text-sm"
                >
                  {fr ? 'Analyser mes données →' : 'Analyse my evidence →'}
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── VERDICT ──────────────────────────────────────────────────────────── */}
      <section className="bg-surface py-14 px-6 border-y border-gray-100">
        <div className="max-w-3xl mx-auto text-center">
          <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">
            {fr ? 'Diagnostic de cohérence' : 'Coherence diagnostic'}
          </p>
          <h2 className="text-2xl font-bold text-primary mb-8">
            {fr ? 'Compatibilité entre revendication et structure de preuve' : 'Compatibility between claim and evidence structure'}
          </h2>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <AlignmentBadge
              color="green"
              label={fr ? 'Cohérent' : 'Coherent'}
              sub={fr
                ? 'La structure de preuve est compatible avec la revendication. Les principaux critères méthodologiques sont alignés.'
                : 'The evidence structure is compatible with the claim. The main methodological criteria are aligned.'}
            />
            <AlignmentBadge
              color="orange"
              label={fr ? 'Partiellement cohérent' : 'Partially coherent'}
              sub={fr
                ? 'Des écarts structurels existent mais peuvent être corrigés par ajustement de design sans refonte complète.'
                : 'Structural gaps exist but can be corrected by design adjustment without a full redesign.'}
            />
            <AlignmentBadge
              color="red"
              label={fr ? 'Non cohérent' : 'Non-coherent'}
              sub={fr
                ? 'Le design ou les mesures ne permettent pas une inférence causale au niveau de la revendication formulée.'
                : 'The design or measurements do not allow causal inference at the level of the formulated claim.'}
            />
          </div>
        </div>
      </section>

      {/* ── EXEMPLE ODYSIGHT ─────────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-5xl mx-auto">
          <p className="text-center text-accent font-semibold text-sm uppercase tracking-widest mb-4">
            {fr ? 'Exemple — Odysight' : 'Example — Odysight'}
          </p>
          <h2 className="text-3xl font-bold text-primary text-center mb-4">
            {fr ? 'Décalage revendication ↔ preuve' : 'Claim ↔ evidence misalignment'}
          </h2>

          <div className="text-center mb-10">
            <div className="inline-block bg-gray-50 border border-gray-200 rounded-xl px-6 py-4 max-w-xl text-left">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-2">
                {fr ? 'Revendication analysée' : 'Claim analysed'}
              </p>
              <p className="text-sm text-gray-700 italic">
                {fr
                  ? `"${ODYSIGHT_CLAIM_FR}"`
                  : `"${ODYSIGHT_CLAIM_EN}"`}
              </p>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            {/* Gaps */}
            <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm">
              <div className="bg-gray-50 border-b border-gray-100 px-5 py-3">
                <span className="font-semibold text-gray-700 text-sm">
                  {fr ? 'Analyse EvidenceAble — 3 écarts identifiés' : 'EvidenceAble analysis — 3 gaps identified'}
                </span>
              </div>
              <div className="divide-y divide-gray-50">
                {exampleGaps.map((g, i) => (
                  <div key={i} className="px-5 py-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="bg-primary/10 text-primary text-xs font-bold px-2 py-0.5 rounded">
                        {fr ? `Écart ${i + 1}` : `Gap ${i + 1}`}
                      </span>
                      <span className="text-xs text-gray-400 font-semibold uppercase tracking-wide">{g.label}</span>
                    </div>
                    <p className="text-sm text-gray-700 leading-relaxed">{g.desc}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Plan */}
            <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm flex flex-col">
              <div className="bg-accent/10 border-b border-accent/20 px-5 py-3">
                <span className="font-semibold text-accent text-sm">
                  {fr ? 'Plan de correction' : 'Correction plan'}
                </span>
              </div>
              <div className="px-5 py-5 flex-1 space-y-4">
                {(fr
                  ? [
                      { effort: '✅ Immédiat', cls: 'bg-green-50 border-green-200 text-green-700', action: 'Reformuler comme revendication de performance mesurée', hint: 'La circularité disparaît si la revendication devient "sensibilité X% pour détecter une évolution ≥ 5 lettres ETDRS vs. bilan mensuel standard". Le design existant devient cohérent.' },
                      { effort: '🔧 Amendement', cls: 'bg-orange-50 border-orange-200 text-orange-700', action: 'Ajouter un groupe comparateur pour établir un contrefactuel', hint: 'Un bras "suivi ophtalmologique standard seul" permet d\'isoler l\'effet du dispositif de l\'histoire naturelle de la DMLA.' },
                      { effort: '🏗 Nouvelle étude', cls: 'bg-red-50 border-red-200 text-red-700', action: 'RCT avec adjudication indépendante des poussées exsudatives', hint: 'Remplacer l\'alerte générée par Odysight par un outcome adjugé indépendamment (OCT centralisé, décision d\'injection de l\'évaluateur en aveugle).' },
                    ]
                  : [
                      { effort: '✅ Immediate', cls: 'bg-green-50 border-green-200 text-green-700', action: 'Reframe as a measured performance claim', hint: 'Circularity disappears if the claim becomes "sensitivity X% to detect a ≥5-letter ETDRS change vs. monthly standard follow-up". The existing design becomes coherent.' },
                      { effort: '🔧 Amendment', cls: 'bg-orange-50 border-orange-200 text-orange-700', action: 'Add a comparator arm to establish a counterfactual', hint: 'A "standard ophthalmological follow-up alone" arm allows isolating the device effect from AMD natural history.' },
                      { effort: '🏗 New study', cls: 'bg-red-50 border-red-200 text-red-700', action: 'RCT with independent adjudication of exudative flares', hint: 'Replace the Odysight-generated alert with an independently adjudicated outcome (centralised OCT, blinded evaluator injection decision).' },
                    ]
                ).map((a, i) => (
                  <div key={i}>
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className={`px-2.5 py-1 rounded-lg text-xs font-semibold border ${a.cls}`}>{a.effort}</span>
                    </div>
                    <p className="text-sm font-medium text-gray-800 mb-1">{a.action}</p>
                    <p className="text-xs text-gray-400 italic border-l-2 border-gray-200 pl-3 leading-relaxed">{a.hint}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-8 text-center">
            <Link
              to={ODYSIGHT_REPAIR_URL}
              className="inline-block bg-accent hover:bg-accent/90 text-white px-8 py-3.5 rounded-xl font-semibold transition-colors shadow-md shadow-accent/20"
            >
              {fr ? 'Lancer l\'analyse complète →' : 'Start full analysis →'}
            </Link>
            <p className="mt-3 text-xs text-gray-400">
              {fr
                ? 'La revendication est pré-chargée. Vous pouvez l\'ajuster et ajouter votre propre abstract ou PDF.'
                : 'The claim is pre-loaded. You can adjust it and add your own abstract or PDF.'}
            </p>
          </div>
        </div>
      </section>

      {/* ── VALIDATION DU CADRE ───────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-surface border-y border-gray-100">
        <div className="max-w-5xl mx-auto">
          <p className="text-center text-accent font-semibold text-sm uppercase tracking-widest mb-4">
            {fr ? 'Validation du cadre' : 'Framework validation'}
          </p>
          <h2 className="text-3xl font-bold text-primary text-center mb-4">
            {fr
              ? 'Règles confrontées à 58 avis CNEDiMTS (2022–2025)'
              : 'Rules validated against 58 CNEDiMTS opinions (2022–2025)'}
          </h2>
          <p className="text-center text-gray-500 mb-3 max-w-2xl mx-auto text-sm leading-relaxed">
            {fr
              ? 'Les règles du moteur ont été élaborées à partir de principes méthodologiques et vérifiées sur un corpus d\'avis publics (PECAN, LATM, LPPR — favorables et défavorables) pour confirmer qu\'elles capturent les motifs récurrents de critique méthodologique.'
              : 'Engine rules were built from methodological principles and verified against a corpus of public opinions (PECAN, LATM, LPPR — favorable and unfavorable) to confirm they capture recurring methodological critique patterns.'}
          </p>
          <p className="text-center text-gray-400 text-xs mb-14 italic max-w-xl mx-auto">
            {fr
              ? 'Ce cadre ne constitue pas une prédiction réglementaire. Il s\'agit d\'une modélisation des principes méthodologiques observés.'
              : 'This framework does not constitute a regulatory prediction. It is a formalisation of observed methodological principles.'}
          </p>

          <div className="grid md:grid-cols-3 gap-6">
            {(fr
              ? [
                  {
                    pattern: 'Incohérence dispositif ↔ population',
                    scale: 'Majorité des dossiers',
                    detail: 'Le demandeur fournit des données issues d\'un autre dispositif, d\'une autre génération, ou d\'une population ne correspondant pas à l\'indication revendiquée.',
                    quote: 'aucune étude spécifique de TUCKY CENTER n\'a été soumise',
                    source: 'CNEDiMTS, 2023',
                  },
                  {
                    pattern: 'Dépendance des critères de jugement',
                    scale: 'Part significative des cas',
                    detail: 'Le critère principal est généré ou influencé par le dispositif évalué. L\'ascertainment de l\'outcome n\'est pas indépendant du bras de traitement.',
                    quote: 'critère de jugement principal reposant sur une alerte générée par le dispositif lui-même',
                    source: 'CNEDiMTS, 2022',
                  },
                  {
                    pattern: 'Insuffisance du design',
                    scale: 'Fraction notable des dossiers',
                    detail: 'Le design ne permet pas d\'inférence causale au niveau de la revendication. Design exploratoire pour une revendication d\'outcome, ou absence de comparateur.',
                    quote: 'cette étude porte sur une partie restreinte de l\'indication revendiquée',
                    source: 'CNEDiMTS, 2023',
                  },
                ]
              : [
                  {
                    pattern: 'Device ↔ population incoherence',
                    scale: 'Majority of dossiers',
                    detail: 'The applicant provides data from another device, another generation, or a population that does not match the claimed indication.',
                    quote: 'no specific study of TUCKY CENTER was submitted',
                    source: 'CNEDiMTS, 2023',
                  },
                  {
                    pattern: 'Endpoint dependency',
                    scale: 'Significant proportion of cases',
                    detail: 'The primary endpoint is generated or influenced by the device under evaluation. Outcome ascertainment is not independent of the treatment arm.',
                    quote: 'primary endpoint based on an alert generated by the device itself',
                    source: 'CNEDiMTS, 2022',
                  },
                  {
                    pattern: 'Insufficient study design',
                    scale: 'Notable fraction of dossiers',
                    detail: 'The design does not permit causal inference at the claim level. Exploratory design for an outcome claim, or no comparator arm.',
                    quote: 'this study covers a restricted part of the claimed indication',
                    source: 'CNEDiMTS, 2023',
                  },
                ]
            ).map((item, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
                <div className="inline-block bg-primary/8 text-primary text-xs font-bold px-3 py-1 rounded-full mb-3">
                  {item.scale}
                </div>
                <h3 className="font-semibold text-gray-800 mb-2">{item.pattern}</h3>
                <p className="text-sm text-gray-600 mb-4 leading-relaxed">{item.detail}</p>
                <div className="bg-surface rounded-lg p-3 border text-xs text-gray-500 italic">
                  &laquo; {item.quote} &raquo;
                  <span className="block text-right text-gray-400 mt-1">— {item.source}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CLOSING ──────────────────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-gradient-to-br from-primary to-primary-light text-white">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">
            {fr
              ? 'La plupart des études ne sont pas incorrectes.'
              : 'Most studies are not flawed.'}
          </h2>
          <p className="text-xl text-white/85 mb-6 leading-relaxed">
            {fr
              ? 'Elles ne sont simplement pas alignées avec la revendication qu\'elles sont censées démontrer.'
              : 'They are simply not aligned with the claim they are supposed to demonstrate.'}
          </p>
          <p className="text-white/60 mb-10 max-w-xl mx-auto text-sm leading-relaxed">
            {fr
              ? 'EvidenceAble structure cet alignement avant que le problème ne devienne un risque de design.'
              : 'EvidenceAble structures this alignment before the problem becomes a design risk.'}
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Link
              to="/odysight/review"
              className="bg-white/15 hover:bg-white/25 text-white border border-white/20 px-8 py-3.5 rounded-xl font-semibold transition-colors backdrop-blur-sm text-left"
            >
              <span className="block">{fr ? 'Analyse rapide' : 'Quick analysis'}</span>
              <span className="block text-xs text-white/60 font-normal mt-0.5">
                {fr ? 'À partir de votre revendication' : 'From your claim'}
              </span>
            </Link>
            <Link
              to={ODYSIGHT_REPAIR_URL}
              className="bg-accent hover:bg-accent/90 text-white px-8 py-3.5 rounded-xl font-semibold transition-colors shadow-lg shadow-accent/30 text-left"
            >
              <span className="block">{fr ? 'Analyse complète' : 'Full analysis'}</span>
              <span className="block text-xs text-white/60 font-normal mt-0.5">
                {fr ? 'Revendication + données cliniques' : 'Claim + clinical data'}
              </span>
            </Link>
          </div>
        </div>
      </section>

    </div>
  )
}

// ── Sub-components ────────────────────────────────────────────────────────────

function AlignmentBadge({ color, label, sub }) {
  const colors = {
    green:  { dot: 'bg-green-500',  text: 'text-green-700',  bg: 'bg-green-50 border-green-200' },
    orange: { dot: 'bg-orange-400', text: 'text-orange-700', bg: 'bg-orange-50 border-orange-200' },
    red:    { dot: 'bg-red-500',    text: 'text-red-700',    bg: 'bg-red-50 border-red-200' },
  }[color]
  return (
    <div className={`flex items-start gap-3 rounded-xl border px-4 py-4 flex-1 ${colors.bg}`}>
      <span className={`w-2.5 h-2.5 rounded-full mt-1.5 flex-shrink-0 ${colors.dot}`} />
      <div>
        <p className={`font-semibold text-sm ${colors.text}`}>{label}</p>
        <p className="text-xs text-gray-500 mt-1 leading-relaxed">{sub}</p>
      </div>
    </div>
  )
}
